### ISSUE TITLE
adb order  flash-archive.sh  alwayls failed

### ISSUE THREAD

**Issue by ray-hb** [m9rco/Genymotion_ARM_Translation#10]
first I push the ARM file into  /sdcard/Download,and i can see it in the dir;
second I did the order : adb shell flash-archive.sh  /sdcard/Download/Genymotion-ARM-Translation_for_6.0.zip,and got an wrong tip:
uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats)
/sdcard/Download/Genymotion-ARM-Translation_for_6.0.zip seems to be a zip archive
[flash_archive] Creating tmp dir
rm: /data/local/tmp/sanitized.zip: No such file or directory
[flash_archive] Unzip archive
unzip: can't open /sdcard/Download/Genymotion-ARM-Translation_for_6.0.zip[.zip]
[ERROR][unzip_archive_in_extract_dir] unzip failed: /sdcard/Download/Genymotion-ARM-Translation_for_6.0.zip
[ERROR]{Result:KO};

**Comment by ray-hb** [comment]
ok, I find the answer. The the path of ARM file must not contain any chinese character

**Comment by m9rco** [comment]
ok
