### ISSUE TITLE
7.x Version doesn't work for me.

### ISSUE THREAD

**Issue by abhay991** [m9rco/Genymotion_ARM_Translation#15]
I am able to install this translation tool but when i try to install apk i get same error as i got in past.

![image](https://user-images.githubusercontent.com/37922548/78347133-a2463400-75bd-11ea-86dc-0407a1e8d7fe.png)

I tried different os and different version but none worked for me. I even tried doing through adb but no success. Am i doing something wrong?

**Comment by jmaneyrol69** [comment]
Did you reboot your virtual device after drag'n dropping the zip file?
Also, you can check if the ARM tools are correctly installed by using `adb shell getprop ro.product.cpu.abilist`. It should return *x86,armeabi-v7a,armeabi*.

**Comment by abhay991** [comment]
Yes, i rebooted device and also it does return 'x86,armeabi-v7a,armeabi'

**Comment by jmaneyrol69** [comment]
What APK are you trying to install? ARM translation only provides armv7, if the application has arm64 code it will not work with Genymotion at all, even with ARM translation tools.

**Comment by abhay991** [comment]
I was trying to install Kik app.

**Comment by jmaneyrol69** [comment]
Kik comes in 2 APK variants, armeabi-v7a and arm64-v8a.
Make sure to use the APK variant for armeabi-v7a, the other one will not work with Genymotion, no matter what.
You should be able to find it here: https://apkpure.com/kik/kik.android/variant/15.21.0.22201-APK

**Comment by abhay991** [comment]
Thanks! I was able to install app but for some reason i can't run it. I guess this might be because i tried to install multiple ARM Translation tools.

![image](https://user-images.githubusercontent.com/37922548/78377119-d5ec8280-75ec-11ea-8d57-7047875e308e.png)

**Comment by jmaneyrol69** [comment]
Not sure and I won't be able to help you much further. You'd better contact Genymotion support at https://www.genymotion.com/contact/ and send them genymotion logs (Help > Generate logs).

**Comment by abhay991** [comment]
> Not sure and I won't be able to help you much further. You'd better contact Genymotion support at https://www.genymotion.com/contact/ and send them genymotion logs (Help > Generate logs).

Yeah I guess i solved the issue. Installing App was key thing here. Regarding app crash I will find solution and try to post here. Thanks alot for help mate.

**Comment by abhay991** [comment]
App Crash issue was due to multiple arm translation tool i installed. I reset my emulator and it's working all fine.
