### ISSUE TITLE
Available Translation Support for lib arm64-v8a?

### ISSUE THREAD

**Issue by sluxzer** [m9rco/Genymotion_ARM_Translation#19]
Hi There, 

I want to run application with lib arm64-v8a, trying all available translation in here but nothing works.

Anyone can give me reference where i should looking?

**Comment by BruhDudeWew** [comment]
I don't think it will get support soon. Genymotion only support x86 emulation

**Comment by sluxzer** [comment]
> I don't think it will get support soon. Genymotion only support x86 emulation

Unfortunately.

Well, thanks for quick reply @JakunGamer .

**Comment by niizam** [comment]
Now ARM64 translation is supported
https://github.com/niizam/Genymotion_A11_libhoudini
