### ISSUE TITLE
5.1 出现错误

### ISSUE THREAD

**Issue by t0rjan** [m9rco/Genymotion_ARM_Translation#2]
系统环境：mac os 10.14.5 (18F132)

Genymotion :2.12.3

**Comment by m9rco** [comment]
我也是5.1鸭， 是什么类型的错误，贴一下我康康

**Comment by t0rjan** [comment]
好，我重新整理了下系统，测试给你看下，还有个事情我想问下，这些都是有官方链接吗，有可能官方会自动更新什么的？

**Comment by t0rjan** [comment]
已解决，判断是系统文件缺失导致

**Comment by m9rco** [comment]
是官方的备份。对对，官方更新我不一定更新，我一般用过了对话  会更新过来

**Comment by t0rjan** [comment]
好，谢谢大佬。

**Comment by t0rjan** [comment]
为什么我在windows执行这个，会自动进行删除？

**Comment by m9rco** [comment]
咦，还会自行删除啊

**Comment by t0rjan** [comment]
是呀，你把它拖动到Genymotion的模拟器里，安装完他就会自动删除了，而且连git库都一起删除了。
