### ISSUE TITLE
Needed for android 9.0 & 10.0

### ISSUE THREAD

**Issue by bkasrnyr** [m9rco/Genymotion_ARM_Translation#22]

**Comment by aavamin** [comment]
+1

**Comment by hithamHL** [comment]
+1

**Comment by jmaneyrol69** [comment]
ARM tools for 8.0 also work for 9.0, but not for 10.0 nor 11.0

+1

**Comment by acmelacross** [comment]
ARM tools for 8.0 also work for 9.0, but not for 10.0 nor 11.0

+1

**Comment by acmelacross** [comment]
ARM tools for 8.0 also work for 9.0, but not for 10.0 nor 11.0

+2

**Comment by m9rco** [comment]
+3

**Comment by panlei** [comment]
+4

**Comment by teella** [comment]
-20

**Comment by bitjerry** [comment]
+5

**Comment by m9rco** [comment]
https://github.com/m9rco/Genymotion_ARM_Translation/pull/27
