### ISSUE TITLE
Do not try to install arm64 android apks in genymotion

### ISSUE THREAD

**Issue by sakurawald** [m9rco/Genymotion_ARM_Translation#29]
staled

**Comment by jmaneyrol69** [comment]
Or use Genymotion Device image product: they have native ARM images on AWS -> https://support.genymotion.com/hc/en-us/articles/360010029677-How-to-run-applications-for-arm64-aarch64-armv8-

**Comment by niizam** [comment]
Here if you want to run ARM64 APK
https://github.com/niizam/Genymotion_A11_libhoudini
